---
title: "Práctica AE2"
author: "Grupo 1"
date: "`r format(Sys.time(), '%d-%m-%Y')`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    
---

```{r carga_librerias, include=FALSE}
library(readr)
library(stringr)
library(swirl)
library(RCurl)
library(XML)
library(httr)
library(ggplot2)

```

# Autores

**Práctica:** Actividad Evaluable 2  
**Asignatura:** Data Driven Security  
**Fecha:** `r format(Sys.time(), '%d-%m-%Y')`  


|Grupo 1 |  
|:--------|  
|Javier Gómez Rodríguez|  
|Fernando Palma Villanueva|  
|Mireia Náger Piazuelo| 

# 1. PIE

```{r}
html <- GET("https://www.mediawiki.org")
content <- content(html, as = "text")
parsedHtml <- htmlParse(content, asText = TRUE)

print(parsedHtml)

 title <- xpathSApply(parsedHtml, "//title", xmlValue)
 texts <- xpathSApply(parsedHtml, "//p", xmlValue)
 links_text <- xpathSApply(parsedHtml, "//a", xmlValue)
 links_url  <- xpathSApply(parsedHtml, "//a", xmlGetAttr, 'href')
 
df <- data.frame(
  Text = links_text,
  Url = links_url,
  Tipo = character(179)
)

class(df)
class(df$Text)
class(df$Url)
class(df$Tipo)

```


```{r}
df_mnp <- data.frame(
  Text = c("Link 1", "Link 2", "Link 3", "Link 4", "Link 5", "Link 6"),
  Url = c("URL 1", "URL 2", "URL 3", "URL 4", "URL 5", "URL 6"),
  Status = c("200", "404", "301", "200", "200", "404")
)

class(df_mnp)
class(df_mnp$Text)
class(df_mnp$Url)
class(df_mnp$Status)

https://www.statology.org/ggplot-pie-chart/

pie(df_mnp$Status, labels = df_mnp$Status, col = topo.colors(6), cex=2)
```
