---
title: "Práctica AE2"
author: "Grupo 1"
date: "`r format(Sys.time(), '%d-%m-%Y')`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    
---

```{r carga_librerias, include=FALSE, cache=TRUE}
library(readr)
library(stringr)
library(swirl)
library(RCurl)
library(XML)
library(httr)
library(dplyr)
library(ggplot2)
library(ggpubr)

```

# Autores

**Práctica:** Actividad Evaluable 2  
**Asignatura:** Data Driven Security  
**Fecha:** `r format(Sys.time(), '%d-%m-%Y')`  


|Grupo 1 |  
|:--------|  
|Javier Gómez Rodríguez|  
|Fernando Palma Villanueva|  
|Mireia Náger Piazuelo| 


# 1. Datos elegantes + Análisis de datos con web scrapping

## Pregunta 1

```{r descarga_pagina, include=FALSE}
base_domain <- "https://www.mediawiki.org"
html <- GET("https://www.mediawiki.org")
content <- content(html, as = "text")
parsedHtml <- htmlParse(content, asText = TRUE)
print(parsedHtml)
```


```{r extrae_contenido, include=FALSE}
 title <- xpathSApply(parsedHtml, "//title", xmlValue)
 texts <- xpathSApply(parsedHtml, "//p", xmlValue)
 links_text <- xpathSApply(parsedHtml, "//a", xmlValue)
 links_url  <- xpathSApply(parsedHtml, "//a", xmlGetAttr, 'href')
```


```{r define_functions, include=FALSE}

categoria_url <- function(url) {
  if (startsWith(url, "/")) {
    return("R")
  }
  else if (startsWith(url, "#")) {
    return("I")
  }
  else if (startsWith(url, "https") || startsWith(url, "http"))  {
    return("A")
  }
  else if (startsWith(url, "//")) {
    return("S")
  }
}

convertir_absoluta <- function(url) {
  if (startsWith(url, "/") || startsWith(url, "#") || startsWith(url, "//")) {
    return(paste(base_domain, url, sep = ""))
  }
  else if (startsWith(url, "https") || startsWith(url, "http"))  {
    return(url)
  }
}

get_status <- function(url) {
  html_head <- HEAD(convertir_absoluta(url))
  return(html_head$status_code)

}

```


```{r crea_df, include=FALSE}
df <- data.frame(
  text = links_text,
  url_relativa = links_url,
  url_absoluta = sapply(links_url, convertir_absoluta),
  tipo_url = sapply(links_url, categoria_url),
  status = sapply(links_url, get_status)
)
```


```{r count_repeated_urls, include=FALSE}
table_df <- left_join(df, count(df, url_relativa), by = "url_relativa")

table_df <- data.frame(
  Enlace = unique(df$url_relativa),
  Visto = count(df, url_relativa)
)

table_df <- left_join



```

```{r imprime_tabla}

table_df <- table(df$url_relativa)

table_df <- data.frame(
  text = links_text,
  url_relativa = links_url,
  url_absoluta = sapply(links_url, convertir_absoluta),
  tipo_url = sapply(links_url, categoria_url)
)
```

ggtexttable(
  df,
  rows = NULL
)

#table_df <- table(df$url_relativa)
#ggplot(table(table_df))

#tabledf <- table(df$url_relativa)
#print(xtable(df))
```



```{r request, include=FALSE}
#df$status <- sapply((df$url_absoluta), function(url) {
#  resp_status(req_perform(request(url)))
#})
# df %>% ggplot(aes(x, y )) + geom_bars()


```

## Pregunta 2
